### PR TITLE
Update unit tests

### PR DESCRIPTION
**Pull request by chrisryan**
Updated phpunit to version 5.
Completed code coverage with additional test.
Tested build with Php7 on ubuntu 16.04.

### CODE REVIEW

**Comment by chrisryan** [comment]
Not sure who owns this. Let me know if you want me to split any of these into separate PRs.

**Comment by chrisryan** [comment]
So i guess adding phpunit 5 support breaks 5.4 and 5.5 support. Let me know if the preference to is remove that change and keep the older versions supported or remove the older version from the supported list.

**Comment by wackyMole** [comment]
Hey @chrisryan, thanks!

phpunit 5 requires PHP 5.6+. If we want to bump the minimum version requirement of PHP  to 5.6 it might be better to bump phpunit to `~5.3` instead of `~5.0`?

**Comment by chrisryan** [comment]
Updated as requested.

**Pull request merged**
